### ISSUE TITLE
No such directory "out_images_clean"

### ISSUE THREAD

**Issue by Tizioincognit0** [leomam/Easy_OCR_Hardsubbed_Videos#1]
When I'm trying to extract subtitles from a video 24 minutes long, I get the following error. I'm using Ubuntu 20.10. This happens also when I run "sudo".
`
Starting Extraction
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    v.cleanFrames()
  File "/home/osboxes/Easy_OCR_Hardsubbed_Videos/Video.py", line 70, in cleanFrames
    framesCleaning(self)
  File "/home/osboxes/Easy_OCR_Hardsubbed_Videos/functions.py", line 217, in framesCleaning
    checkExtractedFile(video)
  File "/home/osboxes/Easy_OCR_Hardsubbed_Videos/functions.py", line 145, in checkExtractedFile
    allFrames = os.listdir(video.getWorkDir() + '/' + OUT_EXTRACT_IMAGES_CLEAN)
FileNotFoundError: [Errno 2] No such file or directory: 'working_directory/video/out_images_clean'
`

**Comment by leomam** [comment]
I'm sorry, it's not yet functional, I have a more advanced version on my computer, I'll push it to github when it's bug-free ;)

**Comment by leomam** [comment]
I pushed the patch for this for now.
I'll try to improve the result of the subtitles, for now it's very buggy.
